#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 TypeScript type checking..."
pnpm tsc --noEmit

echo "🔍 Checking dependencies security..."
pnpm audit

echo "🔍 Checking bundle size..."
pnpm analyze

echo "🔍 Building project..."
pnpm run build

echo "✅ All checks passed successfully!"